name: Periodic API Data Fetcher
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  fetch-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

